# Site settings
title: Olivia Campbell
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer and Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://olivia.campbell.today" # the base hostname & protocol for your site

# Social media profiles
github_username:  oecampbell
facebook_username: oecampbell
linkedin_url: https://uk.linkedin.com/in/oecampbell


# Build settings
markdown: kramdown
