# Site settings
title: Olivia Campbell
description: > # this means to ignore newlines until "baseurl:"
  Junior Web Developer and Web Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social media profiles
github_username:  oecampbell
facebook_username: oecampbell
linkedin_url: https://uk.linkedin.com/in/oecampbell

#White-listed plugins
gems:
  - jekyll-seo-tag
  #- jekyll-sitemap

# Build settings
markdown: kramdown
