# Site settings
title: Olivia Campbell
description: > # this means to ignore newlines until "baseurl:"
  Junior Frontend Developer + Web Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: oecampbell
github_username:  oecampbell
facebook_username: oecampbell
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://uk.linkedin.com/in/oecampbell

#Address information
#address_street: London
#address_city: UK
#address_state:
#address_zip:

#White-listed plugins
gems:
  - jekyll-seo-tag
  #- jekyll-sitemap

# Build settings
markdown: kramdown
